### ISSUE TITLE
Drop support for HAXM

### ISSUE THREAD

**Issue by Darin755** [MateuszKrawczuk/QtEmu#10]
Intel MAXM was discontinued in 2023.  

https://github.com/intel/haxm

Since it was continued Qemu is dropping support as well. The recommended alternative is hyper-v based acceleration which QtEmu already supports.

**Comment by MateuszKrawczuk** [comment]
HAXM support from QEMU was dropped, but some users still rely on it. In certain cases, Hyper-V is unavailable or has its own issues, but users can still use HAXM. Therefore, I don't think removing HAXM support entirely is a good idea just because it has been dropped officially. I'm planning to restrict HAXM support to specific versions of QEMU that still maintain compatibility with it.

**Comment by Darin755** [comment]
Maybe you could instead make hyper-v based acceleration the default? Maybe you could make it the last option and then have some brief text noting that it is not officially supported by Intel. At some point HAXM will stop working entirely as more and more updates happen.
