### ISSUE TITLE
I'll be the first then. No accelerators found

### ISSUE THREAD

**Issue by KoghaandSooga** [MateuszKrawczuk/QtEmu#3]
(Sigh)

On Windows 10 64 Bits no matter which accelerator you choose it will say that it can't find said accelerator when pressing the play button. At least it tells you the error this time where as previous it would just not do anything.  Still not supported for Windows yet.  It's sad QEMU isn't for Windows I'm curious as to what OS it's really made for and would most optimize on?

**Comment by MateuszKrawczuk** [comment]
Hello. First of all. Qemu works on Windows with acceleration using HyperV.  To use any acceleration on Windows you have to enable correct extensions in Uefi/Bios. Depending on platform it is AMD SVM or Intel VT. To use HyperV you also need to enable it in Windows. To use alternative acceleration you have to disable HyperV( Blame Microsoft for that). Additionally HyperV by default doesn't support nested Virtualization(Creating virtual machine in other virtual machine best example is launching androisld emulator on Linux )and you have to do some tricks to enable it because by default Microsoft decided to not allow created nested virtualization.

Best experience with Qemu is on Linux with KVM. It also supports Xen but other acceleration doesn't work. I used GVM/AEHD on Windows.


Working acceleration on Qemu(Windows) is:
HyperV 
TCG(default option)
HAXM(only Intel and deprecated)
GVM/AEHD (Wip created by Google for Android Emulator which is based on QEMU)
Biggest different between Qemu and alternative is ability to execute code for other architectures like Arm, mips or risc-v.
